from django.contrib.auth.models import User
from django.db import models
from django.forms import IntegerField


class LoadTeacher(models.Model):
    # Учебная нагрузка
    x = models.IntegerField(default=0, null=True)
    # Методическая нагрузка
    y1 = models.IntegerField(default=0, null=True)
    y3 = models.IntegerField(default=0, null=True)
    y5 = models.IntegerField(default=0, null=True)
    y7 = models.IntegerField(default=0, null=True)
    y9 = models.IntegerField(default=0, null=True)
    y11 = models.IntegerField(default=0, null=True)
    y13 = models.IntegerField(default=0, null=True)
    y15 = models.IntegerField(default=0, null=True)
    y17 = models.IntegerField(default=0, null=True)
    y19 = models.IntegerField(default=0, null=True)
    y21 = models.IntegerField(default=0, null=True)
    y23 = models.IntegerField(default=0, null=True)
    y25 = models.IntegerField(default=0, null=True)
    y27 = models.IntegerField(default=0, null=True)
    y29 = models.IntegerField(default=0, null=True)
    y31 = models.IntegerField(default=0, null=True)
    y32 = models.IntegerField(default=0, null=True)
    y34 = models.IntegerField(default=0, null=True)
    y36 = models.IntegerField(default=0, null=True)
    y38 = models.IntegerField(default=0, null=True)
    y39 = models.IntegerField(default=0, null=True)
    y41 = models.IntegerField(default=0, null=True)
    y43 = models.IntegerField(default=0, null=True)
    y45 = models.IntegerField(default=0, null=True)
    y47 = models.IntegerField(default=0, null=True)
    y49 = models.IntegerField(default=0, null=True)
    y50 = models.IntegerField(default=0, null=True)
    y51 = models.IntegerField(default=0, null=True)
    y53 = models.IntegerField(default=0, null=True)
    y532 = models.IntegerField(default=0, null=True)
    y55 = models.IntegerField(default=0, null=True)
    y57 = models.IntegerField(default=0, null=True)
    y59 = models.IntegerField(default=0, null=True)
    y61 = models.IntegerField(default=0, null=True)
    y63 = models.IntegerField(default=0, null=True)
    y65 = models.IntegerField(default=0, null=True)
    y67 = models.IntegerField(default=0, null=True)
    y69 = models.IntegerField(default=0, null=True)
    y71 = models.IntegerField(default=0, null=True)
    y731 = models.IntegerField(default=0, null=True)
    y732 = models.IntegerField(default=0, null=True)
    y733 = models.IntegerField(default=0, null=True)
    y734 = models.IntegerField(default=0, null=True)
    y75 = models.IntegerField(default=0, null=True)
    y76 = models.IntegerField(default=0, null=True)
    y77 = models.IntegerField(default=0, null=True)
    y79 = models.IntegerField(default=0, null=True)
    y80 = models.IntegerField(default=0, null=True)
    y82 = models.IntegerField(default=0, null=True)
    y84 = models.IntegerField(default=0, null=True)
    y86 = models.IntegerField(default=0, null=True)
    y88 = models.IntegerField(default=0, null=True)
    y90 = models.IntegerField(default=0, null=True)
    y92 = models.IntegerField(default=0, null=True)
    y94 = models.IntegerField(default=0, null=True)
    y96 = models.IntegerField(default=0, null=True)
    y98 = models.IntegerField(default=0, null=True)
    y99 = models.IntegerField(default=0, null=True)
    y100 = models.IntegerField(default=0, null=True)
    y102 = models.IntegerField(default=0, null=True)
    # Научная нагрузка
    z = models.IntegerField(default=0, null=True)
    z2 = models.IntegerField(default=0, null=True)
    z4 = models.IntegerField(default=0, null=True)
    z6 = models.IntegerField(default=0, null=True)
    z8 = models.IntegerField(default=0, null=True)
    z10 = models.IntegerField(default=0, null=True)
    z12 = models.IntegerField(default=0, null=True)
    z13 = models.IntegerField(default=0, null=True)
    z14 = models.IntegerField(default=0, null=True)
    z15 = models.IntegerField(default=0, null=True)
    z16 = models.IntegerField(default=0, null=True)
    z18 = models.IntegerField(default=0, null=True)
    z19 = models.IntegerField(default=0, null=True)
    z20 = models.IntegerField(default=0, null=True)
    z21 = models.IntegerField(default=0, null=True)
    z23 = models.IntegerField(default=0, null=True)
    z25 = models.IntegerField(default=0, null=True)
    z27 = models.IntegerField(default=0, null=True)
    z29 = models.IntegerField(default=0, null=True)
    z31 = models.IntegerField(default=0, null=True)
    z33 = models.IntegerField(default=0, null=True)
    z36 = models.IntegerField(default=0, null=True)
    z38 = models.IntegerField(default=0, null=True)
    # Командирская подготовка
    f1 = models.IntegerField(default=0, null=True)
    f2 = models.IntegerField(default=0, null=True)
    f3 = models.IntegerField(default=0, null=True)
    f4 = models.IntegerField(default=0, null=True)
    f5 = models.IntegerField(default=0, null=True)
    f6 = models.IntegerField(default=0, null=True)
    # Другие виды работ
    g1 = models.IntegerField(default=0, null=True)
    g2 = models.IntegerField(default=0, null=True)

    date_creation = models.DateField(auto_now=True, verbose_name="Дата создания")

    user = models.ForeignKey(User, on_delete=models.PROTECT, verbose_name="Пользователь")

    class Meta:
        verbose_name = "Нагрузка преподователя"
        verbose_name_plural = "Нагрузки преподователей"

    @staticmethod
    def available_requests(user):
        return LoadTeacher.objects.filter(user=user)
